branches:
  only:
    - master

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules

install:
  - npm install
script:
  - npm test
  - npm run build
  - cd dist/
  - git init
  - git config user.name ${UID}
  - git config user.email ${EMAIL}
  - git add .
  - git commit -m "Deploy"
  - git push --force --quiet https://${TOKEN}@github.com/vv13/nho-demo.git master:gh-pages